---
version: "3.8"
services:
  ui:
    build: ./ui
    ports:
      - 8080:8080
    volumes:
      - ./ui:/app/
  api:
    build: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server:/app/